# Generated by Django 2.2.12 on 2020-05-30 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jservice_id', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jservice_id', models.IntegerField(db_index=True, unique=True)),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('value', models.PositiveIntegerField(default=200)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jeopardy.Category')),
            ],
        ),
    ]
