# Generated by Django 2.2.12 on 2020-05-30 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
        ('jeopardy', '0002_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest.Bot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turn',
            name='currently_active',
            field=models.BooleanField(default=True),
        ),
    ]
