# Generated by Django 2.2.12 on 2020-05-30 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeopardy', '0003_auto_20200530_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='clue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jeopardy.Clue'),
        ),
    ]
